kind: ExternalService
name: result
spec:
  image: fandoghpaas/result:${VERSION}
  env:
    - name: PGPASSWORD
      value: db123
      hidden: true
    - name: ENVKEY
      value: myvariable
  resources:
    memory: 100Mi
